INSERT INTO USUARIOS (TIPOUSUARIO,NOMBRE, CONTRASENA) VALUES ('administrador','admin1','admin1');
INSERT INTO USUARIOS (TIPOUSUARIO,NOMBRE, CONTRASENA) VALUES ('administrador','admin2','admin2');
INSERT INTO USUARIOS (TIPOUSUARIO,NOMBRE, CONTRASENA) VALUES ('administrador','admin3','admin3');

INSERT INTO USUARIOS (TIPOUSUARIO,NOMBRE, CONTRASENA) VALUES ('usuario','usr1','usr1');
INSERT INTO USUARIOS (TIPOUSUARIO,NOMBRE, CONTRASENA) VALUES ('usuario','usr2','usr2');
INSERT INTO USUARIOS (TIPOUSUARIO,NOMBRE, CONTRASENA) VALUES ('usuario','usr3','usr3');

